name: Build
on: 
  push:
    branches: ['withXMLtags']
  pull_request:
    branches: ['withXMLtags']


jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: linux-latest

    steps:
    
      - name: Installing
        run: '!sudo apt update'

      - name: Installing
        run: '!sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev'

      - name: Installing
        run: '!pip3 install --user --upgrade Cython==0.29.33 virtualenv'

      - name: Installing
        run: '!git clone https://github.com/kivy/buildozer'

      - name: Installing
        run: '%cd buildozer'

      - name: Installing
        run: '!python setup.py build'

      - name: Installing
        run: '!pip install -e .'

      - name: Installing
        run: '%cd ..'

      - name: Installing
        run: '!buildozer -v android debug'



  
