name: Build
on: 
  push:
    branches: ['withXMLtags']
  pull_request:
    branches: ['withXMLtags']


jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Installing
        run: 'sudo apt-get update'

      - name: Installing
        run: 'sudo apt-get install build-essential'

      - name: Installing
        run: 'sudo apt-get install libstdc++6'
          
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          run: 'sudo apt-get install aidl'
          workdir: .
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}


  
